- targets:
  - "172.80.14.3:9100"
  - "172.80.14.4:9100"
  - "172.80.14.7:9100"
  - "172.80.14.5:19100"
  - "172.80.14.10:9100"
  - "172.80.14.11:9100"
  - "172.80.14.24:9100"
  - "172.80.14.17:9100"
  - "172.80.14.18:9100"
  - "172.80.14.19:9100"
  - "172.80.14.99:9100"
  - "172.80.14.82:9100"
  - "172.80.14.80:9100"
  - "172.80.14.96:9100"
  - "172.80.14.95:9100"
  - "172.80.14.100:9100"
  - "172.80.14.101:9100"
  - "172.80.14.102:9100"
  - "172.80.14.103:9100"
  - "172.80.14.104:9100"
  - "172.80.14.105:9100"
  - "172.80.14.106:9100"
  - "172.80.14.107:9100"
