settings:
  application:
    # dev开发环境 test测试环境 prod线上环境
    mode: prod
    # 服务器ip，默认使用 0.0.0.0
    host: 0.0.0.0
    # 服务名称
    name: testApp
    # 端口号
    port: 8000 # 服务端口号
    readtimeout: 1
    writertimeout: 2
    # 数据权限功能开关
    enabledp: false
  logger:
    # 日志存放路径
    path: temp/logs
    # 日志输出，file：文件，default：命令行，其他：命令行
    stdout: '' #控制台日志，启用后，不输出到文件
    # 日志等级, trace, debug, info, warn, error, fatal
    level: trace
    # 数据库日志开关
    enableddb: true
  jwt:
    # token 密钥，生产环境时及的修改
    secret: 6pjMOgsd
    # token 过期时间 单位：秒
    timeout: 36000
  database:
    # 数据库类型 mysql, sqlite3, postgres, sqlserver
    # sqlserver: sqlserver://用户名:密码@地址?database=数据库名
    driver: mysql
    # 数据库连接字符串 mysql 缺省信息 charset=utf8&parseTime=True&loc=Local&timeout=1000ms
    source: root:rroott2&s*!666@tcp(mysql_db:3306)/goadmin?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  gen:
    # 代码生成读取的数据库名称
    dbname: goadmin
    # 代码生成是使用前端代码存放位置，需要指定到src文件夹，相对路径
    frontpath: ../go-admin-ui/src
  extend: # 扩展项使用说明
    mongodb:
      uri: "mongodb://root:7ZnbNNWC@mongo_db:27017"
      db: "admin"
    redis:
      address: "redis_db:6379"
      password: "9OEQ@izZ3"
      db: 0
    logger:
      # 日志存放路径
      path: logs
      # 日志输出，file：文件，default：命令行，其他：命令行
      stdout: true  #控制台日志，启用后 同时输出到控制台和文件
      # 日志等级, trace, debug, info, warn, error, fatal
      level: info
    external:
      url: "http://video_tools:28080"
      grafana: "http://grafana:3000"
      stream: "http://video_tools:7080"
      kibana: "http://kibana_skyeye:5601"
      jaeger: "http://jq_skyeye:16686"
  queue:
    memory:
      poolSize: 100
  #    redis:
  #      addr: 127.0.0.1:6379
  #      password: xxxxxx
  #      producer:
  #        streamMaxLength: 100
  #        approximateMaxLength: true
  #      consumer:
  #        visibilityTimeout: 60
  #        bufferSize: 100
  #        concurrency: 10
  #        blockingTimeout: 5
  #        reclaimInterval: 1
  locker:
    redis:
